minimaliste_poster_quiz_admin:
    resource: "@MinimalistePosterQuizBundle/Resources/config/admin-routing.yml"
    prefix:   /admin

minimaliste_poster_quiz_front:
    resource: "@MinimalistePosterQuizBundle/Resources/config/front-routing.yml"
    prefix:   /
